/**
 * PrismaJson Types Integration Example
 *
 * This example demonstrates how to use Prismocker with PrismaJson types
 * from prisma-json-types-generator. It shows how to work with strongly-typed
 * JSON fields and how Prismocker preserves type safety for JSON data.
 *
 * Key Features Demonstrated:
 * - PrismaJson type definitions
 * - Strongly-typed JSON fields
 * - JSON field validation
 * - Nested JSON structures
 * - Type-safe JSON queries
 *
 * Prerequisites:
 * - prisma-json-types-generator configured in schema.prisma
 * - Generated PrismaJson types available
 *
 * NOTE: This example uses generic model names (content, companies) that should
 * be adapted to match your actual Prisma schema. The patterns shown here
 * work with any Prisma models and fields.
 */

import { describe, it, expect, beforeEach } from '@jest/globals';
import { createPrismocker } from '../src/index.js';
import type { PrismaClient } from '@prisma/client';
import { resetAndSeed } from '../src/test-utils.js';

// Type-safe helper to work with any PrismaClient
type AnyPrismaClient = PrismaClient;

/**
 * Example PrismaJson type definitions
 *
 * In a real application, these would be generated by prisma-json-types-generator:
 *
 * ```typescript
 * // Generated by prisma-json-types-generator
 * namespace PrismaJson {
 *   type ContentMetadata = {
 *     dependencies: string[];
 *     tags: string[];
 *     author?: {
 *       name: string;
 *       email: string;
 *     };
 *   };
 *
 *   type CompanySettings = {
 *     theme: 'light' | 'dark' | 'auto';
 *     notifications: {
 *       email: boolean;
 *       push: boolean;
 *     };
 *     features: {
 *       [key: string]: boolean;
 *     };
 *   };
 * }
 * ```
 *
 * For this example, we'll define mock types to demonstrate the pattern.
 */

// Mock PrismaJson types (replace with generated types in real usage)
namespace PrismaJson {
  export type ContentMetadata = {
    dependencies: string[];
    tags: string[];
    author?: {
      name: string;
      email: string;
    };
  };

  export type CompanySettings = {
    theme: 'light' | 'dark' | 'auto';
    notifications: {
      email: boolean;
      push: boolean;
    };
    features: {
      [key: string]: boolean;
    };
  };
}

describe('PrismaJson Types Integration', () => {
  let prisma: AnyPrismaClient;

  beforeEach(() => {
    prisma = createPrismocker<PrismaClient>();

    resetAndSeed(prisma, {
      content: [
        {
          id: 'content-1',
          slug: 'example-content',
          title: 'Example Content',
          metadata: {
            dependencies: ['react', 'typescript'],
            tags: ['tutorial', 'react'],
            author: {
              name: 'John Doe',
              email: 'john@example.com',
            },
          } as PrismaJson.ContentMetadata,
        },
      ] as any,
      companies: [
        {
          id: 'company-1',
          name: 'Acme Corp',
          slug: 'acme-corp',
          owner_id: 'user-1',
          settings: {
            theme: 'dark',
            notifications: {
              email: true,
              push: false,
            },
            features: {
              analytics: true,
              reporting: false,
            },
          } as PrismaJson.CompanySettings,
        },
      ] as any,
    });
  });

  describe('Creating Records with PrismaJson Types', () => {
    it('should create record with strongly-typed JSON field', async () => {
      const metadata: PrismaJson.ContentMetadata = {
        dependencies: ['react', 'vue'],
        tags: ['framework', 'javascript'],
        author: {
          name: 'Jane Doe',
          email: 'jane@example.com',
        },
      };

      const content = await (prisma as any).content.create({
        data: {
          slug: 'new-content',
          title: 'New Content',
          metadata,
        },
      });

      expect(content.metadata).toEqual(metadata);
      expect(content.metadata.dependencies).toEqual(['react', 'vue']);
      expect(content.metadata.author?.name).toBe('Jane Doe');
    });

    it('should create record with optional JSON fields', async () => {
      const metadata: PrismaJson.ContentMetadata = {
        dependencies: [],
        tags: [],
        // author is optional
      };

      const content = await (prisma as any).content.create({
        data: {
          slug: 'minimal-content',
          title: 'Minimal Content',
          metadata,
        },
      });

      expect(content.metadata.dependencies).toEqual([]);
      expect(content.metadata.author).toBeUndefined();
    });

    it('should preserve type safety when querying JSON fields', async () => {
      const content = await (prisma as any).content.findUnique({
        where: { slug: 'example-content' },
      });

      if (content?.metadata) {
        // TypeScript knows the structure of metadata
        expect(content.metadata.dependencies).toBeDefined();
        expect(Array.isArray(content.metadata.dependencies)).toBe(true);
        expect(content.metadata.tags).toBeDefined();
        expect(content.metadata.author?.name).toBe('John Doe');
      }
    });
  });

  describe('Updating Records with PrismaJson Types', () => {
    it('should update JSON field with strongly-typed data', async () => {
      const updatedMetadata: PrismaJson.ContentMetadata = {
        dependencies: ['react', 'vue', 'angular'],
        tags: ['framework', 'javascript', 'typescript'],
        author: {
          name: 'Updated Author',
          email: 'updated@example.com',
        },
      };

      const updated = await (prisma as any).content.update({
        where: { slug: 'example-content' },
        data: {
          metadata: updatedMetadata,
        },
      });

      expect(updated.metadata.dependencies).toHaveLength(3);
      expect(updated.metadata.author?.name).toBe('Updated Author');
    });

    it('should partially update JSON field', async () => {
      // Update only specific properties of JSON field
      const updated = await (prisma as any).content.update({
        where: { slug: 'example-content' },
        data: {
          metadata: {
            dependencies: ['react', 'typescript', 'nextjs'],
            tags: ['tutorial', 'react', 'nextjs'],
            // author remains unchanged
          },
        },
      });

      expect(updated.metadata.dependencies).toContain('nextjs');
      // Author should still exist from original data
      expect(updated.metadata.author?.name).toBe('John Doe');
    });
  });

  describe('Querying JSON Fields', () => {
    it('should query records by JSON field properties', async () => {
      // Query by JSON field property (if supported by your Prisma version)
      // Note: Prismocker supports basic JSON path queries
      const content = await (prisma as any).content.findMany({
        where: {
          // Example: Query by JSON field property
          // This depends on your Prisma schema and Prismocker's JSON query support
        },
      });

      expect(content.length).toBeGreaterThan(0);
    });

    it('should filter by nested JSON properties', async () => {
      // Create content with specific metadata
      await (prisma as any).content.create({
        data: {
          slug: 'react-content',
          title: 'React Tutorial',
          metadata: {
            dependencies: ['react'],
            tags: ['react', 'tutorial'],
          } as PrismaJson.ContentMetadata,
        },
      });

      // Query all content
      const allContent = await (prisma as any).content.findMany();

      // Filter in JavaScript (Prismocker may support JSON path queries in future)
      const reactContent = allContent.filter((c: any) =>
        c.metadata?.dependencies?.includes('react')
      );

      expect(reactContent.length).toBeGreaterThan(0);
      expect(reactContent.every((c: any) => c.metadata.dependencies.includes('react'))).toBe(true);
    });
  });

  describe('Complex JSON Structures', () => {
    it('should handle deeply nested JSON structures', async () => {
      const complexMetadata: PrismaJson.ContentMetadata = {
        dependencies: ['react', 'typescript', '@types/react'],
        tags: ['tutorial', 'react', 'typescript'],
        author: {
          name: 'Complex Author',
          email: 'complex@example.com',
        },
      };

      const content = await (prisma as any).content.create({
        data: {
          slug: 'complex-content',
          title: 'Complex Content',
          metadata: complexMetadata,
        },
      });

      expect(content.metadata.dependencies).toHaveLength(3);
      expect(content.metadata.author?.name).toBe('Complex Author');
    });

    it('should handle JSON arrays', async () => {
      const metadata: PrismaJson.ContentMetadata = {
        dependencies: ['dep1', 'dep2', 'dep3'],
        tags: ['tag1', 'tag2'],
      };

      const content = await (prisma as any).content.create({
        data: {
          slug: 'array-content',
          title: 'Array Content',
          metadata,
        },
      });

      expect(Array.isArray(content.metadata.dependencies)).toBe(true);
      expect(content.metadata.dependencies.length).toBe(3);
      expect(Array.isArray(content.metadata.tags)).toBe(true);
      expect(content.metadata.tags.length).toBe(2);
    });
  });

  describe('Type Safety with PrismaJson', () => {
    it('should enforce type safety for JSON fields', () => {
      // TypeScript will catch type errors at compile time
      const validMetadata: PrismaJson.ContentMetadata = {
        dependencies: ['react'],
        tags: ['tutorial'],
        author: {
          name: 'Author',
          email: 'author@example.com',
        },
      };

      // This should compile without errors
      expect(validMetadata).toBeDefined();

      // Invalid metadata would cause TypeScript errors:
      // const invalidMetadata: PrismaJson.ContentMetadata = {
      //   dependencies: 'not-an-array', // ❌ Type error
      //   tags: 123, // ❌ Type error
      // };
    });

    it('should preserve type information through Prisma operations', async () => {
      const metadata: PrismaJson.ContentMetadata = {
        dependencies: ['react'],
        tags: ['tutorial'],
      };

      const content = await (prisma as any).content.create({
        data: {
          slug: 'typed-content',
          title: 'Typed Content',
          metadata,
        },
      });

      // Type information is preserved
      expect(content.metadata).toBeDefined();
      expect(Array.isArray(content.metadata.dependencies)).toBe(true);
      expect(Array.isArray(content.metadata.tags)).toBe(true);
    });
  });

  describe('Company Settings Example', () => {
    it('should work with different PrismaJson types', async () => {
      const settings: PrismaJson.CompanySettings = {
        theme: 'dark',
        notifications: {
          email: true,
          push: true,
        },
        features: {
          analytics: true,
          reporting: true,
          export: false,
        },
      };

      const company = await (prisma as any).companies.create({
        data: {
          name: 'New Company',
          slug: 'new-company',
          owner_id: 'user-1',
          settings,
        },
      });

      expect(company.settings.theme).toBe('dark');
      expect(company.settings.notifications.email).toBe(true);
      expect(company.settings.features.analytics).toBe(true);
    });

    it('should update company settings', async () => {
      const updatedSettings: PrismaJson.CompanySettings = {
        theme: 'light',
        notifications: {
          email: false,
          push: true,
        },
        features: {
          analytics: false,
          reporting: true,
        },
      };

      const updated = await (prisma as any).companies.update({
        where: { slug: 'acme-corp' },
        data: {
          settings: updatedSettings,
        },
      });

      expect(updated.settings.theme).toBe('light');
      expect(updated.settings.notifications.email).toBe(false);
      expect(updated.settings.features.analytics).toBe(false);
    });
  });
});
