/**
 * Prisma Ecosystem Compatibility Layer
 *
 * Ensures Prismocker is fully compatible with the Prisma ecosystem:
 * - Prisma Client Extensions ($extends)
 * - Generated Zod schemas (prisma-zod-generator)
 * - PrismaJson types (prisma-json-types-generator)
 * - Custom generators and plugins
 *
 * This module provides utilities and type definitions that make Prismocker
 * work seamlessly with all Prisma-generated types and extensions.
 *
 * @example
 * ```typescript
 * import { createPrismocker } from 'prismocker';
 * import type { PrismaClient } from '@prisma/client';
 * import { CompaniesCreateInputSchema } from '@prisma/zod'; // Generated Zod schema
 *
 * const prisma = createPrismocker<PrismaClient>();
 *
 * // ✅ Works with generated Zod schemas
 * const data = CompaniesCreateInputSchema.parse({ name: 'Test' });
 * await prisma.companies.create({ data });
 *
 * // ✅ Works with PrismaJson types
 * const jsonData: PrismaJson.ContentMetadata = { dependencies: [] };
 * await prisma.content.create({ data: { metadata: jsonData } });
 * ```
 */

import type { PrismaClient } from '@prisma/client';

/**
 * PrismaJson namespace type (from prisma-json-types-generator)
 *
 * This type is augmented by prisma-json-types-generator to provide
 * strongly typed Json fields. Prismocker should respect these types.
 *
 * @example
 * ```typescript
 * // In schema.prisma:
 * // model Content {
 * //   metadata Json? /// [ContentMetadata]
 * // }
 *
 * // Generated by prisma-json-types-generator:
 * // namespace PrismaJson {
 * //   type ContentMetadata = { ... }
 * // }
 *
 * const metadata: PrismaJson.ContentMetadata = { dependencies: [] };
 * ```
 */
export type PrismaJson = typeof globalThis extends { PrismaJson: infer T }
  ? T
  : Record<string, unknown>;

/**
 * Options for Prisma ecosystem integration
 */
export interface PrismaEcosystemOptions {
  /**
   * Enable Zod schema validation for create/update operations
   *
   * When enabled, Prismocker will validate data against generated Zod schemas
   * if they are available. This requires prisma-zod-generator to be configured.
   *
   * @default false
   */
  validateWithZod?: boolean;

  /**
   * Path to generated Zod schemas
   *
   * Defaults to '@prisma/zod' or '@heyclaude/database-types/prisma/zod'
   * depending on your generator configuration.
   *
   * @default '@prisma/zod'
   */
  zodSchemasPath?: string;

  /**
   * Custom Zod schema loader function
   *
   * Allows custom loading logic for Zod schemas (e.g., from custom paths).
   *
   * @param modelName - Model name (e.g., 'companies', 'jobs')
   * @param operation - Operation type ('create', 'update', 'where', etc.)
   * @returns Zod schema or undefined if not available
   */
  zodSchemaLoader?: (
    modelName: string,
    operation: 'create' | 'update' | 'where' | 'select' | 'include'
  ) => Promise<any> | any | undefined;
}

/**
 * Dynamic import helper that works even when module is not installed.
 *
 * Uses Function constructor to bypass TypeScript's static import checking.
 * This allows importing optional dependencies like 'zod' without type errors
 * when the module may or may not be installed.
 *
 * @param modulePath - The module path to import (e.g., 'zod', '@prisma/zod')
 * @returns The imported module, or `null` if import fails
 *
 * @internal This function is used internally for optional dependency loading
 */
async function dynamicImport(modulePath: string): Promise<any> {
  try {
    // Use Function constructor to create a dynamic import that TypeScript won't check
    // This is safe because we control the modulePath parameter
    // eslint-disable-next-line @typescript-eslint/no-implied-eval
    const importFn = new Function('modulePath', 'return import(modulePath)');
    return await importFn(modulePath);
  } catch {
    return null;
  }
}

/**
 * Checks if Zod validation is available for use with Prismocker.
 *
 * Attempts to dynamically import Zod and check if schemas are available.
 * This allows Prismocker to work even if Zod schemas aren't generated or
 * if the `zod` package isn't installed.
 *
 * @param zodSchemasPath - Path to Zod schemas (default: '@prisma/zod')
 * @returns `true` if Zod validation is available, `false` otherwise
 *
 * @example
 * ```typescript
 * const isAvailable = await isZodValidationAvailable();
 * if (isAvailable) {
 *   // Enable Zod validation
 *   const prisma = createPrismocker({ validateWithZod: true });
 * }
 * ```
 */
export async function isZodValidationAvailable(
  zodSchemasPath: string = '@prisma/zod'
): Promise<boolean> {
  try {
    // Try to import Zod (optional dependency)
    const zodModule = await dynamicImport('zod');
    if (!zodModule || !zodModule.z) return false;

    // Try to import a sample schema to verify path is correct
    // This is a best-effort check - actual validation will handle errors
    try {
      await dynamicImport(zodSchemasPath);
      return true;
    } catch {
      // Path might be different, but Zod is available
      return true;
    }
  } catch {
    return false;
  }
}

/**
 * Validates data against a Zod schema with enhanced error messages.
 *
 * This function validates data using a generated Zod schema (from prisma-zod-generator).
 * If validation fails, it throws a descriptive error with helpful suggestions for fixing
 * the validation issues.
 *
 * @param schema - Zod schema to validate against (from prisma-zod-generator)
 * @param data - Data to validate (should match the schema)
 * @param modelName - Model name for error messages (e.g., 'companies', 'jobs')
 * @param operation - Operation type for error messages ('create' or 'update')
 * @returns Validated data (parsed and potentially transformed by Zod)
 * @throws {Error} If validation fails, with detailed error message including validation issues
 *
 * @example
 * ```typescript
 * const schema = await loadZodSchema('companies', 'create');
 * const validated = validateWithZod(schema, { name: 'Test' }, 'companies', 'create');
 * ```
 *
 * @see {@link loadZodSchema} for loading Zod schemas
 */
export function validateWithZod(
  schema: any,
  data: any,
  modelName: string,
  operation: 'create' | 'update'
): any {
  if (!schema || typeof schema.parse !== 'function') {
    // Schema not available, skip validation
    return data;
  }

  try {
    return schema.parse(data);
  } catch (error: any) {
    const dataPreview = JSON.stringify(data, null, 2).slice(0, 500);
    const issues = error.issues
      ? JSON.stringify(error.issues, null, 2)
      : 'No detailed issues available';

    throw new Error(
      `Prismocker: Zod validation failed for ${modelName}.${operation}\n\n` +
        `Validation error: ${error.message}\n\n` +
        `Data being validated:\n${dataPreview}${dataPreview.length >= 500 ? '...' : ''}\n\n` +
        (error.issues ? `Validation issues:\n${issues}\n\n` : '') +
        `This usually means:\n` +
        `  1. The data doesn't match the Zod schema requirements\n` +
        `  2. Required fields are missing or have wrong types\n` +
        `  3. The Zod schema path is incorrect or schema is outdated\n\n` +
        `To fix:\n` +
        `  - Check that all required fields are present and correctly typed\n` +
        `  - Verify your Zod schema path: ${modelName}${operation === 'create' ? 'CreateInputSchema' : 'UpdateInputSchema'}\n` +
        `  - Regenerate Zod schemas: npx prisma generate\n` +
        `  - Disable Zod validation: createPrismocker({ validateWithZod: false })\n` +
        `  - Check the validation issues above for specific field problems`
    );
  }
}

/**
 * Loads a generated Zod schema for a specific model and operation.
 *
 * This function attempts to dynamically import a Zod schema from the configured
 * path. It constructs the schema name based on Prisma's naming conventions:
 * - Model name is converted to PascalCase (e.g., 'companies' → 'Companies')
 * - Operation is mapped to schema suffix (e.g., 'create' → 'CreateInputSchema')
 * - Final schema name: `CompaniesCreateInputSchema`
 *
 * **Supported operations:**
 * - `create` → `{Model}CreateInputSchema`
 * - `update` → `{Model}UpdateInputSchema`
 * - `where` → `{Model}WhereInputSchema`
 * - `select` → `{Model}SelectSchema`
 * - `include` → `{Model}IncludeSchema`
 *
 * @param modelName - Model name (e.g., 'companies', 'jobs')
 * @param operation - Operation type ('create', 'update', 'where', 'select', 'include')
 * @param zodSchemasPath - Path to Zod schemas (default: '@prisma/zod')
 * @returns Zod schema if available, or `undefined` if not found
 *
 * @example
 * ```typescript
 * const createSchema = await loadZodSchema('companies', 'create');
 * if (createSchema) {
 *   const validated = createSchema.parse({ name: 'Test' });
 * }
 * ```
 *
 * @see {@link validateWithZod} for validating data with loaded schemas
 */
export async function loadZodSchema(
  modelName: string,
  operation: 'create' | 'update' | 'where' | 'select' | 'include',
  zodSchemasPath: string = '@prisma/zod'
): Promise<any | undefined> {
  try {
    // Convert model name to PascalCase (e.g., 'companies' -> 'Companies')
    const pascalModelName = modelName.charAt(0).toUpperCase() + modelName.slice(1);

    // Map operation to schema suffix
    const schemaSuffixMap: Record<string, string> = {
      create: 'CreateInputSchema',
      update: 'UpdateInputSchema',
      where: 'WhereInputSchema',
      select: 'SelectSchema',
      include: 'IncludeSchema',
    };

    const schemaName = `${pascalModelName}${schemaSuffixMap[operation] || 'InputSchema'}`;

    // Try to import the schema using dynamic import
    const schemas = await dynamicImport(zodSchemasPath);
    if (!schemas) return undefined;

    return schemas[schemaName];
  } catch {
    // Schema not available - this is fine, validation is optional
    return undefined;
  }
}

/**
 * Type helper for Prisma Client with extensions
 *
 * This type represents a PrismaClient that may have been extended
 * with custom extensions using `$extends()`.
 *
 * @template TBase - Base PrismaClient type
 * @template TExtensions - Extension type (from $extends)
 */
export type ExtendedPrismaClient<
  TBase extends PrismaClient = PrismaClient,
  TExtensions = unknown,
> = TBase & TExtensions;

/**
 * Check if a PrismaClient instance has been extended
 *
 * Prisma Client extensions are added via `$extends()` method.
 * This function checks if extensions are present.
 *
 * @param prisma - PrismaClient instance to check
 * @returns True if the client has been extended
 */
export function hasExtensions(prisma: PrismaClient): boolean {
  // Extensions are typically added via $extends() which returns a new client
  // We can check for custom properties that aren't part of the base PrismaClient
  // This is a best-effort check - extensions are transparent at runtime
  return false; // Extensions are transparent, so we can't reliably detect them
}

/**
 * Apply Prisma Client extensions to PrismockerClient
 *
 * This function allows applying Prisma Client extensions to a PrismockerClient
 * instance, making it compatible with extended Prisma clients.
 *
 * Note: Prisma extensions are typically applied via `$extends()` which returns
 * a new client. Prismocker should support this pattern.
 *
 * @param prisma - PrismockerClient instance
 * @param extensions - Extension configuration (same format as Prisma's $extends)
 * @returns Extended PrismockerClient
 *
 * @example
 * ```typescript
 * const prisma = createPrismocker<PrismaClient>();
 * const extended = applyExtensions(prisma, {
 *   model: {
 *     companies: {
 *       async findActive() {
 *         return prisma.companies.findMany({ where: { active: true } });
 *       },
 *     },
 *   },
 * });
 * ```
 */
export function applyExtensions<T extends PrismaClient>(prisma: T, extensions: any): T {
  // Prisma's $extends() creates a new client with extensions
  // For Prismocker, we can simulate this by adding methods to the proxy
  // This is a simplified implementation - full support would require
  // implementing Prisma's extension system

  // For now, return the client as-is
  // Full extension support would require implementing Prisma's extension system
  // which is complex and may not be necessary for most use cases
  return prisma;
}

/**
 * Type-safe helper to create Prismocker with ecosystem support
 *
 * This is a convenience function that creates a PrismockerClient with
 * ecosystem compatibility options pre-configured.
 *
 * @param options - Prismocker and ecosystem options
 * @returns PrismockerClient instance with ecosystem support
 *
 * @example
 * ```typescript
 * const prisma = createPrismockerWithEcosystem({
 *   validateWithZod: true,
 *   zodSchemasPath: '@prisma/zod',
 * });
 * ```
 */
export function createPrismockerWithEcosystem<T extends PrismaClient>(
  options?: import('./types.js').PrismockerOptions
): T {
  // Import createPrismocker dynamically to avoid circular dependencies
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { createPrismocker } = require('./index.js');
  return createPrismocker(options) as T;
}
